name: build

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
        default: latest
    outputs:
      artifact_name:
        description: The artifact name of the build
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact_name: dist-${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: false
            - args: [--global, typescript]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm i

      - name: Build
        id: build
        run: pnpm run build
      
      - name: Upload build artifacts
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist/
          retention-days: 5