name: release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      body:
        type: string
        required: true
      artifact_name:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./

      - name: Prepare release assets
        run: |
          zip ${{ github.event.repository.name }}-v${{ inputs.version }}.esm.zip *.mjs *.d.mts **/*.mjs **/*.d.mts
          zip ${{ github.event.repository.name }}-v${{ inputs.version }}.cjs.zip *.js *.d.ts **/*.js **/*.d.ts
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ inputs.body }}
          tag_name: ${{ inputs.version }}
          name: v${{ inputs.version }}
          make_latest: true
          files: |
            ${{ github.event.repository.name }}-v${{ inputs.version }}.esm.zip
            ${{ github.event.repository.name }}-v${{ inputs.version }}.cjs.zip