name: test

on:
  workflow_call:

jobs:
  typecheck:

    outputs:
      outcome: ${{ steps.typecheck.outcome }}
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: false
            - args: [--global, typescript]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm i
      
      - name: Typecheck
        id: typecheck
        continue-on-error: true
        run: tsc --noEmit
