name: version

on:
  workflow_call:
    outputs:
      new_release_version:
        description: The new version that was released
        value: ${{ jobs.version.outputs.new_release_version }}
      new_release_notes:
        description: The changelog of the release
        value: ${{ jobs.version.outputs.new_release_notes }}
        
jobs:
  version:
    runs-on: ubuntu-latest

    outputs:
      new_release_version: ${{ steps.version.outputs.new_release_version }}
      new_release_notes: ${{ steps.version.outputs.new_release_notes }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: false
            - args: [--global, typescript]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Version and release
        id: version
        uses: cycjimmy/semantic-release-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19.0.5
          dry_run: true
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
