name: ci/pull_request

run-name: ${{ github.actor }} pushed to a pull request.

on:
  push:
    branches-ignore:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    uses: fxfn/actions/.github/workflows/typecheck.yml@v1
  
  test:
    uses: fxfn/actions/.github/workflows/test.yml@v1